# install-services.yml

---
  - hosts: loadbalancers
    become: true
    tasks:
      - name: Installing Apache
        apt: name=apache2 state=present update_cache=yes
      - name: Ensure apache starts
        service: name=apache2 state=started enabled=yes

  - hosts: webservers
    become: true
    tasks:
      - name: Installing Apache & PHP
        apt:
          name:
            - apache2
            - php
            - php-pear
            - php-zip
          state: present
          update_cache: yes
      - name: Ensure apache starts
        service: name=apache2 state=started enabled=yes
